### DISCUSSION TITLE
Changes in 4C input and consequences for QUEENS

### DISCUSSION THREAD

**Discussion by gilrrei** [queens-py/queens#172] [Announcements]
There have been a lot of changes in the 4C input world (which is great, much thanks to @sebproell for the work). The big changes in a nutshell:
- Move to YAML and JSON from dat
  - **Consequences for QUEENS**: no need to use Jinja2
  - Whereas YAML is more human readable than JSON, from a performance POV JSON is recommended for QUEENS since it is faster to read and dump. So I think the recommended way is JSON, especially if a lot of simulations are required (not available yet)
- Includes feature
  - 4C allows for splitting up the input into multiple files and referencing them in the `INCLUDES` section
  - **Consequences for QUEENS**: Copy the data that remains constant to a child 4C file that lives in the experiment directory, such that in the job directly file would only contain:
    ```yaml
    TITLE:
      - Job_id: 272 # this is not needed but it is nice to have some more information :)
    section with changing params:
      - param: 1
      - param2: some varying value
    INCLUDES:
      - ../root_file.4C.yaml
    ```
  - This allows for reducing data, and it is easier to spot what changed. Btw this should make the input construction faster in QUEENS as only affected sections have to be written
- Random Fields
  - Currently ongoing work, but @sebproell, @maxiludwig, and @lauraengelhardt introduced the feature to provide a (JSON) file mapping between element ID and material parameters. @maxfirmbach already deployed it to a material, and it looks super cool
  - **Consequences for QUEENS**: no need for custom material readers and writers (about 1000 lines of code). The only thing we now need is a way to extract the element centers of the input files (which with fourcipp is only a couple of lines of code), see 4C-multiphysics/4C#890 or 4C-multiphysics/4C#893
  - 
Great work, the interoperability of 4Q increased a lot! Much thanks to all the people who did the work, from concepts to documentation and implementation.
